// @ts-nocheck
// AUTO-GENERATED by tauri-specta. Do NOT edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Smoke-command: returns version from Cargo.toml. Proves tauri-specta wiring works.
 */
async appVersion() : Promise<AppVersion> {
    return await TAURI_INVOKE("app_version");
},
/**
 * Cache-first contract describe. On a cache hit, returns the cached catalog
 * WITHOUT opening a channel (auto-reflect-on-blur fires often). On a miss,
 * `activate()` reflects + populates the cache, then the connection is dropped.
 */
async grpcDescribe(target: GrpcTargetIpc) : Promise<Result<ServiceCatalogIpc, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grpc_describe", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manual refresh: invalidate the cache entry then re-reflect.
 */
async grpcRefreshContract(target: GrpcTargetIpc) : Promise<Result<ServiceCatalogIpc, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grpc_refresh_contract", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build a JSON skeleton from the cached pool. On a cache miss, activate first.
 */
async grpcBuildRequestSkeleton(target: GrpcTargetIpc, service: string, method: string) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grpc_build_request_skeleton", { target, service, method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One-shot unary invoke: activate (channel required) → invoke → drop.
 * 
 * Non-OK gRPC status arrives in `InvokeOutcomeIpc.status_code`, NOT as `Err`.
 * `Err` is only for client-side failures (transport / encode / decode).
 * The descriptor pool is reused from the `ContractCache` when present; only the channel is opened fresh per call.
 */
async grpcInvokeOneshot(target: GrpcTargetIpc, request: InvokeRequest) : Promise<Result<InvokeOutcomeIpc, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grpc_invoke_oneshot", { target, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async envList() : Promise<Result<EnvironmentIpc[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("env_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async envActiveGet() : Promise<Result<string | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("env_active_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async envActiveSet(name: string | null) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("env_active_set", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async envUpsert(env: EnvironmentIpc) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("env_upsert", { env }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async envDelete(name: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("env_delete", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async varsResolve(template: string) : Promise<Result<ResolutionReportIpc, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vars_resolve", { template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectionList() : Promise<Result<CollectionMetaIpc[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collection_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectionGet(id: string) : Promise<Result<CollectionIpc, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collection_get", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectionUpsert(collection: CollectionIpc) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collection_upsert", { collection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectionDelete(id: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collection_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectionSetVariables(id: string, vars: Partial<{ [key in string]: string }>) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collection_set_variables", { id, vars }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectionAddItem(collectionId: string, parentId: string | null, item: ItemIpc) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collection_add_item", { collectionId, parentId, item }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectionRenameItem(collectionId: string, itemId: string, name: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collection_rename_item", { collectionId, itemId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectionMoveItem(collectionId: string, itemId: string, newParentId: string | null, position: number) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collection_move_item", { collectionId, itemId, newParentId, position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectionDuplicateItem(collectionId: string, itemId: string) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collection_duplicate_item", { collectionId, itemId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectionDeleteItem(collectionId: string, itemId: string) : Promise<Result<ItemSnapshotIpc | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collection_delete_item", { collectionId, itemId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async collectionRestoreItem(collectionId: string, snapshot: ItemSnapshotIpc, parentId: string | null, position: number) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("collection_restore_item", { collectionId, snapshot, parentId, position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authSetForEnv(collectionId: string, itemId: string | null, envName: string, config: SavedAuthConfigIpc | null) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_set_for_env", { collectionId, itemId, envName, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
contractUpdated: ContractUpdated
}>({
contractUpdated: "contract-updated"
})

/** user-defined constants **/



/** user-defined types **/

export type AppVersion = { version: string }
export type AuthByEnvIpc = { configs: Partial<{ [key in string]: SavedAuthConfigIpc }> }
export type CollectionIpc = { id: string; name: string; items: ItemIpc[]; variables: Partial<{ [key in string]: string }>; auth_by_env: AuthByEnvIpc; default_tls: boolean; skip_tls_verify: boolean }
/**
 * Lightweight list entry (id + name only) for `collection_list`.
 */
export type CollectionMetaIpc = { id: string; name: string }
/**
 * Emitted whenever a target's contract has been (re)built (describe / refresh).
 */
export type ContractUpdated = { 
/**
 * Stable key identifying the target whose contract just refreshed.
 */
target_key: string }
export type EnvironmentIpc = { name: string; variables: Partial<{ [key in string]: string }> }
export type FolderIpc = { id: string; name: string; items: ItemIpc[]; auth_by_env: AuthByEnvIpc }
export type GrpcTargetIpc = { address: string; tls: boolean; skip_verify: boolean }
export type InvokeOutcomeIpc = { status_code: number; status_message: string; response_json: string | null; trailing_metadata: Partial<{ [key in string]: string }>; 
/**
 * Elapsed time in milliseconds. Capped at u32::MAX (~49 days) for
 * TypeScript compatibility (specta forbids u64 / BigInt at the IPC boundary).
 */
elapsed_ms: number }
export type InvokeRequest = { service: string; method: string; request_json: string; metadata: Partial<{ [key in string]: string }> }
export type IpcError = { type: "InvalidTarget"; message: string } | { type: "NotConnected" } | { type: "ReflectionDisabled"; hint: string } | { type: "Reflection"; message: string } | { type: "DescriptorBuild"; message: string } | { type: "ServiceNotFound"; service: string } | { type: "MethodNotFound"; service: string; method: string } | { type: "EncodeRequest"; message: string } | { type: "DecodeResponse"; message: string } | { type: "UnresolvedVariable"; name: string } | { type: "VariableCycle"; chain: string[] } | { type: "Transport"; message: string } | { type: "Auth"; message: string } | { type: "GrpcStatus"; code: number; message: string } | { type: "NotImplemented"; message: string } | { type: "Persistence"; message: string }
export type ItemIpc = ({ type: "folder" } & FolderIpc) | ({ type: "request" } & SavedRequestIpc)
/**
 * Undo payload returned by `collection_delete_item`.
 */
export type ItemSnapshotIpc = { item: ItemIpc; parent_id: string | null; position: number }
export type MethodEntryIpc = { name: string; path: string; input_message: string; output_message: string; client_streaming: boolean; server_streaming: boolean }
export type ResolutionReportIpc = { resolved: string; unresolved_vars: string[]; cycle_chain: string[] | null }
export type SavedAuthConfigIpc = { kind: "none" } | { kind: "env_var"; env_var: string; header_name: string; prefix: string } | { kind: "oauth_2_client_credentials"; token_url: string; client_id: string; client_secret_env_var: string; scopes: string[] }
export type SavedRequestIpc = { id: string; name: string; address_template: string; service: string; method: string; body_template: string; metadata: Partial<{ [key in string]: string }>; auth_by_env: AuthByEnvIpc; tls_override: boolean | null }
export type ServiceCatalogIpc = { services: ServiceEntryIpc[] }
export type ServiceEntryIpc = { full_name: string; methods: MethodEntryIpc[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
