// @ts-nocheck
// AUTO-GENERATED by tauri-specta. Do NOT edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Smoke-command: returns version from Cargo.toml. Proves tauri-specta wiring works.
 */
async appVersion() : Promise<AppVersion> {
    return await TAURI_INVOKE("app_version");
},
async grpcConnect(input: ConnectInput) : Promise<Result<ConnectOutcome, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grpc_connect", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async grpcDisconnect() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grpc_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async grpcRefreshContract() : Promise<Result<ServiceCatalogIpc, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grpc_refresh_contract") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send unary RPC through the active connection.
 * 
 * `Result<InvokeOutcomeIpc, IpcError>` — non-OK gRPC status arrives in
 * `InvokeOutcomeIpc.status_code`, NOT as `Err`. Err is only for client-side
 * failures (NotConnected, transport, encode/decode).
 */
async grpcInvokeUnary(request: InvokeRequest) : Promise<Result<InvokeOutcomeIpc, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grpc_invoke_unary", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build a JSON skeleton for the request body of the given method.
 */
async grpcBuildRequestSkeleton(service: string, method: string) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grpc_build_request_skeleton", { service, method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async envList() : Promise<Result<EnvironmentIpc[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("env_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async envActiveGet() : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("env_active_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async envActiveSet(name: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("env_active_set", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async envUpsert(env: EnvironmentIpc) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("env_upsert", { env }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async varsResolve(template: string) : Promise<Result<ResolutionReportIpc, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vars_resolve", { template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
connectionStateChanged: ConnectionStateChanged,
contractUpdated: ContractUpdated
}>({
connectionStateChanged: "connection-state-changed",
contractUpdated: "contract-updated"
})

/** user-defined constants **/



/** user-defined types **/

export type AppVersion = { version: string }
export type ConnectInput = { address: string; tls: boolean; skip_verify: boolean }
export type ConnectOutcome = { target: TargetSummary; catalog: ServiceCatalogIpc }
/**
 * Emitted on connect / disconnect.
 */
export type ConnectionStateChanged = { connected: boolean; target: TargetSummary | null }
/**
 * Emitted whenever the active connection's contract has been (re)built.
 */
export type ContractUpdated = { 
/**
 * Stable key identifying the target whose contract just refreshed.
 */
target_key: string }
export type EnvironmentIpc = { name: string; variables: Partial<{ [key in string]: string }> }
export type InvokeOutcomeIpc = { status_code: number; status_message: string; response_json: string | null; trailing_metadata: Partial<{ [key in string]: string }>; 
/**
 * Elapsed time in milliseconds. Capped at u32::MAX (~49 days) for
 * TypeScript compatibility (specta forbids u64 / BigInt at the IPC boundary).
 */
elapsed_ms: number }
export type InvokeRequest = { service: string; method: string; request_json: string; metadata: Partial<{ [key in string]: string }> }
export type IpcError = { type: "InvalidTarget"; message: string } | { type: "NotConnected" } | { type: "ReflectionDisabled"; hint: string } | { type: "Reflection"; message: string } | { type: "DescriptorBuild"; message: string } | { type: "ServiceNotFound"; service: string } | { type: "MethodNotFound"; service: string; method: string } | { type: "EncodeRequest"; message: string } | { type: "DecodeResponse"; message: string } | { type: "UnresolvedVariable"; name: string } | { type: "VariableCycle"; chain: string[] } | { type: "Transport"; message: string } | { type: "Auth"; message: string } | { type: "GrpcStatus"; code: number; message: string } | { type: "NotImplemented"; message: string }
export type MethodEntryIpc = { name: string; path: string; input_message: string; output_message: string; client_streaming: boolean; server_streaming: boolean }
export type ResolutionReportIpc = { resolved: string; unresolved_vars: string[]; cycle_chain: string[] | null }
export type ServiceCatalogIpc = { services: ServiceEntryIpc[] }
export type ServiceEntryIpc = { full_name: string; methods: MethodEntryIpc[] }
export type TargetSummary = { address: string; tls: boolean; skip_verify: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
