import type { CollectionIpc } from "@/ipc/bindings";

/**
 * In-memory sample data used when running outside of a Tauri context (browser dev / Storybook).
 * Mirrors the shape of `CollectionIpc` with realistic-looking gRPC request nodes.
 */
export const SAMPLE_COLLECTIONS: CollectionIpc[] = [
  {
    id: "col-checkout",
    name: "Checkout flow",
    variables: { base_url: "orders.api.example.com:443" },
    auth_by_env: { configs: {} },
    default_tls: true,
    skip_tls_verify: false,
    items: [
      {
        type: "request",
        id: "req-create-order",
        name: "Create order",
        address_template: "orders.api.example.com:443",
        service: "checkout.v1.OrderService",
        method: "CreateOrder",
        body_template: '{\n  "userId": "{{userId}}",\n  "items": []\n}',
        metadata: {},
        auth_by_env: { configs: {} },
        tls_override: true,
      },
      {
        type: "request",
        id: "req-get-order",
        name: "Get order",
        address_template: "orders.api.example.com:443",
        service: "checkout.v1.OrderService",
        method: "GetOrder",
        body_template: '{\n  "orderId": "{{orderId}}"\n}',
        metadata: {},
        auth_by_env: { configs: {} },
        tls_override: true,
      },
      {
        type: "folder",
        id: "folder-payment",
        name: "Payment",
        auth_by_env: { configs: {} },
        items: [
          {
            type: "request",
            id: "req-charge",
            name: "Charge",
            address_template: "payments.api.example.com:443",
            service: "payments.v1.PaymentService",
            method: "Charge",
            body_template: '{\n  "orderId": "{{orderId}}",\n  "amount": 0\n}',
            metadata: {},
            auth_by_env: { configs: {} },
            tls_override: true,
          },
          {
            type: "request",
            id: "req-refund",
            name: "Refund",
            address_template: "payments.api.example.com:443",
            service: "payments.v1.PaymentService",
            method: "Refund",
            body_template: '{\n  "paymentId": "{{paymentId}}"\n}',
            metadata: {},
            auth_by_env: { configs: {} },
            tls_override: true,
          },
        ],
      },
    ],
  },
  {
    id: "col-identity",
    name: "Identity & Access",
    variables: {},
    auth_by_env: { configs: {} },
    default_tls: true,
    skip_tls_verify: false,
    items: [
      {
        type: "request",
        id: "req-register",
        name: "Register",
        address_template: "identity.api.example.com:443",
        service: "identity.v1.UsersService",
        method: "Register",
        body_template: '{\n  "email": "alice@example.com",\n  "password": "{{password}}"\n}',
        metadata: {},
        auth_by_env: { configs: {} },
        tls_override: true,
      },
      {
        type: "request",
        id: "req-authenticate",
        name: "Authenticate",
        address_template: "identity.api.example.com:443",
        service: "identity.v1.UsersService",
        method: "Authenticate",
        body_template: '{\n  "email": "alice@example.com",\n  "password": "{{password}}"\n}',
        metadata: {},
        auth_by_env: { configs: {} },
        tls_override: true,
      },
      {
        type: "request",
        id: "req-profile",
        name: "Profile",
        address_template: "identity.api.example.com:443",
        service: "identity.v1.UsersService",
        method: "Profile",
        body_template: "{}",
        metadata: {},
        auth_by_env: { configs: {} },
        tls_override: true,
      },
    ],
  },
  {
    id: "col-sandbox",
    name: "Sandbox",
    variables: {},
    auth_by_env: { configs: {} },
    default_tls: false,
    skip_tls_verify: true,
    items: [
      {
        type: "request",
        id: "req-health",
        name: "Health check",
        address_template: "localhost:5002",
        service: "grpc.health.v1.Health",
        method: "Check",
        body_template: '{\n  "service": ""\n}',
        metadata: {},
        auth_by_env: { configs: {} },
        tls_override: false,
      },
      {
        type: "request",
        id: "req-reflection",
        name: "",
        address_template: "localhost:5002",
        service: "grpc.reflection.v1alpha.ServerReflection",
        method: "ServerReflectionInfo",
        body_template: "{}",
        metadata: {},
        auth_by_env: { configs: {} },
        tls_override: false,
      },
    ],
  },
];
