//! Standalone binary that regenerates `src/ipc/bindings.ts`.
//!
//! `cargo build` doesn't reach the export call inside `lib.rs::run()` (which
//! only fires when the windowed app starts), and integration tests in this
//! crate fail with `STATUS_ENTRYPOINT_NOT_FOUND` on Windows because their
//! linkage against the lib's mixed staticlib/cdylib/rlib produces a binary
//! whose import table can't be satisfied without the full Tauri main-binary
//! setup. A real `[[bin]]` mirrors the main exe's linkage and works.
//!
//! Gated behind the `export-bindings` Cargo feature so `tauri build` does not try
//! to bundle it. Run with:
//!
//!     cargo run -p handshaker --bin export-bindings --features export-bindings

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use handshaker_lib::specta_builder;
use specta_typescript::Typescript;

fn main() {
    let cwd = std::env::current_dir().expect("cwd");
    println!("cwd: {}", cwd.display());

    // Resolve relative to this source file's location (CARGO_MANIFEST_DIR is
    // set at compile time to `src-tauri/`), so the path is independent of
    // wherever `cargo run` is invoked from.
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let out = std::path::Path::new(manifest_dir)
        .join("..")
        .join("src")
        .join("ipc")
        .join("bindings.ts");
    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent).expect("create parent dir");
    }
    println!("writing: {}", out.display());

    specta_builder()
        .export(
            Typescript::default()
                .formatter(specta_typescript::formatter::prettier)
                .header(
                    "// @ts-nocheck\n\
                     // AUTO-GENERATED by tauri-specta. Do NOT edit.\n",
                ),
            &out,
        )
        .expect("failed to export tauri-specta bindings");

    println!("wrote {}", out.display());
}
