//! Handshaker Tauri shell library.

pub mod commands;
pub mod ipc;
mod state;

use commands::events::{ConnectionStateChanged, ContractUpdated};
use commands::grpc::{
    grpc_build_request_skeleton, grpc_connect, grpc_disconnect, grpc_invoke_unary,
    grpc_refresh_contract,
};
use commands::meta::app_version;
use specta_typescript::Typescript;
use state::AppState;
use tauri_specta::{collect_commands, collect_events, Builder};

/// Build a `tauri_specta::Builder` populated with every command and event the
/// app exposes. Used by both `run()` and the `export-bindings` helper binary.
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            app_version,
            grpc_connect,
            grpc_disconnect,
            grpc_refresh_contract,
            grpc_invoke_unary,
            grpc_build_request_skeleton,
        ])
        .events(collect_events![ContractUpdated, ConnectionStateChanged])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Install rustls' default crypto provider once at process start. tonic 0.14 with
    // `tls-ring` does NOT install it automatically; without this the first TLS handshake
    // panics with "no process-level CryptoProvider available".
    rustls::crypto::ring::default_provider()
        .install_default()
        .expect("install rustls ring provider");

    let specta_builder = specta_builder();

    #[cfg(debug_assertions)]
    {
        let out = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("src")
            .join("ipc")
            .join("bindings.ts");
        specta_builder
            .export(
                Typescript::default()
                    .formatter(specta_typescript::formatter::prettier)
                    .header(
                        "// @ts-nocheck\n\
                         // AUTO-GENERATED by tauri-specta. Do NOT edit.\n",
                    ),
                &out,
            )
            .expect("failed to export tauri-specta bindings");
    }

    tauri::Builder::default()
        .manage(AppState::default())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            specta_builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
