//! Handshaker Tauri shell library.
//!
//! The library form exists so that mobile entry points (and tests) can call
//! `run()` directly. `main.rs` is a thin wrapper that delegates here on desktop.

pub mod commands;
pub mod ipc;
mod state;

use commands::meta::{app_version, AppReady};
use specta_typescript::Typescript;
use state::AppState;
use tauri_specta::{collect_commands, collect_events, Builder};

/// Build a `tauri_specta::Builder` populated with every command and event the
/// app exposes. Used by both `run()` and the `export-bindings` helper binary.
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![app_version])
        .events(collect_events![AppReady])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let specta_builder = specta_builder();

    // Regenerate TS bindings on every debug build that boots the app.
    // Note: `cargo build` doesn't reach this path. For deterministic
    // regeneration without launching the windowed app, run:
    //
    //     cargo run -p handshaker --bin export-bindings
    //
    // The path is anchored at CARGO_MANIFEST_DIR (= `src-tauri/`) so it works
    // regardless of where the binary is invoked from.
    #[cfg(debug_assertions)]
    {
        let out = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("src")
            .join("ipc")
            .join("bindings.ts");
        specta_builder
            .export(
                Typescript::default()
                    .formatter(specta_typescript::formatter::prettier)
                    .header(
                    "// @ts-nocheck\n\
                     // AUTO-GENERATED by tauri-specta. Do NOT edit.\n",
                ),
                &out,
            )
            .expect("failed to export tauri-specta bindings");
    }

    tauri::Builder::default()
        .manage(AppState::default())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            specta_builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
