//! Handshaker Tauri shell library.

pub mod commands;
pub mod ipc;
mod state;

use commands::auth::{auth_invalidate, auth_oauth2_fetch_token, auth_resolve};
use commands::base64::{base64_inspect, base64_save, base64_save_encoded};
use commands::collection::{
    collection_add_item, collection_bump_usage, collection_delete, collection_delete_item,
    collection_duplicate_item, collection_get, collection_list, collection_move_item,
    collection_move_item_across, collection_rename_item, collection_restore_item, collection_set_expanded,
    collection_set_node_auth, collection_set_variables, collection_upsert,
};
use commands::env::{env_active_get, env_active_set, env_delete, env_list, env_reorder, env_upsert};
use commands::events::ContractUpdated;
use commands::grpc::{
    grpc_build_request_skeleton, grpc_cancel, grpc_describe, grpc_invoke_oneshot,
    grpc_message_schema, grpc_refresh_contract,
};
use commands::meta::app_version;
use commands::bundle::{bundle_export, bundle_import_apply, bundle_import_inspect};
use commands::ui_state::{app_settings_get, app_settings_set};
use commands::vars::vars_resolve;
use specta_typescript::Typescript;
use state::AppState;
use tauri::Manager;
use tauri_specta::{collect_commands, collect_events, Builder};

/// Build a `tauri_specta::Builder` populated with every command and event the
/// app exposes. Used by both `run()` and the `export-bindings` helper binary.
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            app_version,
            grpc_describe,
            grpc_refresh_contract,
            grpc_build_request_skeleton,
            grpc_message_schema,
            grpc_invoke_oneshot,
            grpc_cancel,
            env_list,
            env_active_get,
            env_active_set,
            env_upsert,
            env_delete,
            env_reorder,
            vars_resolve,
            base64_inspect,
            base64_save,
            base64_save_encoded,
            auth_resolve,
            auth_oauth2_fetch_token,
            auth_invalidate,
            collection_list,
            collection_get,
            collection_upsert,
            collection_delete,
            collection_set_variables,
            collection_add_item,
            collection_rename_item,
            collection_move_item,
            collection_move_item_across,
            collection_duplicate_item,
            collection_delete_item,
            collection_restore_item,
            collection_set_node_auth,
            collection_set_expanded,
            collection_bump_usage,
            app_settings_get,
            app_settings_set,
            bundle_export,
            bundle_import_inspect,
            bundle_import_apply,
        ])
        .events(collect_events![ContractUpdated])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Install rustls' default crypto provider once at process start. tonic 0.14 with
    // `tls-ring` does NOT install it automatically; without this the first TLS handshake
    // panics with "no process-level CryptoProvider available".
    rustls::crypto::ring::default_provider()
        .install_default()
        .expect("install rustls ring provider");

    let specta_builder = specta_builder();

    #[cfg(debug_assertions)]
    {
        let out = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("src")
            .join("ipc")
            .join("bindings.ts");
        specta_builder
            .export(
                Typescript::default()
                    .formatter(specta_typescript::formatter::prettier)
                    .header(
                        "// @ts-nocheck\n\
                         // AUTO-GENERATED by tauri-specta. Do NOT edit.\n",
                    ),
                &out,
            )
            .expect("failed to export tauri-specta bindings");
    }

    tauri::Builder::default()
        .invoke_handler(specta_builder.invoke_handler())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_decorum::init())
        .plugin(tauri_plugin_dialog::init())
        .setup(move |app| {
            specta_builder.mount_events(app);
            let data_dir = app
                .path()
                .app_data_dir()
                .expect("resolve app_data_dir");
            let state = AppState::load(&data_dir)
                .expect("initialize AppState from data dir");
            app.manage(state);

            // macOS: vertically center the native traffic lights in our 36px (h-9)
            // titlebar. decorum repositions the buttons and — unlike the static
            // `trafficLightPosition` config — re-applies after resize / fullscreen-exit,
            // fixing the position reset. y=16 centers a ~20px-tall button cluster in the
            // 36px bar (button center = (button_height + y) / 2 ≈ 18). Tune via the inset.
            #[cfg(target_os = "macos")]
            {
                use tauri_plugin_decorum::WebviewWindowExt;
                if let Some(win) = app.get_webview_window("main") {
                    let _ = win.set_traffic_lights_inset(14.0, 16.0);
                }
            }

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
